### ISSUE TITLE
Error when upload app with PayCardsRecognizer.framework !

### ISSUE THREAD

**Issue by Vitalik13** [faceterteam/PayCards_iOS_Source#2]
I added manual framework and testing all ready, but when I want upload my project in itunesconnect for testing with TestFlight.
I got next warning
<img width="746" alt="2017-11-07 12 23 00" src="https://user-images.githubusercontent.com/17448005/32487153-e221ee92-c3b9-11e7-8cf8-e00a901eece6.png">
 Then I got next errors
<img width="950" alt="2017-11-07 12 41 56" src="https://user-images.githubusercontent.com/17448005/32487152-e1fb6f88-c3b9-11e7-88bc-306b376296b2.png">
**Please help me!**

**Comment by vitkuzmenko** [comment]
Hello! Bitcode is enabled for your app?

**Comment by vitkuzmenko** [comment]
we got this error when trying to submit with the bitcode off

**Comment by Vitalik13** [comment]
My app have bitcode is enabled

**Comment by vitkuzmenko** [comment]
Try install framework from cocoapods.

**Comment by Vitalik13** [comment]
I need change border color from scan view and if I add with cocoapods. I cann't change color.

**Comment by vitkuzmenko** [comment]
Try to install from cocoapods and change pictures in /Pods/PayCardsRecognizer/PayCardsRecognizer.framework. We add modifying frame colors soon...

**Comment by Vitalik13** [comment]
<img width="572" alt="2017-11-07 13 35 48" src="https://user-images.githubusercontent.com/17448005/32489385-d8c355d2-c3c0-11e7-80e3-1361c6432b93.png">

**Comment by vitkuzmenko** [comment]
pod update

**Comment by vitkuzmenko** [comment]
You also can clone https://github.com/faceterteam/PayCards_iOS_Source then make some changes and build project. After, use builded PayCardsRecognizer.framework in project folder.

**Comment by Vitalik13** [comment]
У тебя XCode 9.1? 
Просто Alamofire устанавливается и через pod и вручную. А тут что то не понятное твориться ( ты пробывал собирать этот framework на XCode 9.1?

**Comment by vitkuzmenko** [comment]
Important! All targets uses in project should bitcode is on!

**Comment by Vitalik13** [comment]
Я изначально так сделал и у меня всё работала при тестировании, но когда я начал заливать для TestFlight. В таргет приложении тоже bitcode включён

**Comment by vitkuzmenko** [comment]
Давай сначала разберемся с cocoapods, сделай не pod install а pod update. видимо старая база спеков у тебя

**Comment by Vitalik13** [comment]
Уже сделал сейчас попробую залить и отпишусь))

**Comment by tchernitski** [comment]
Also pay your attention to https://github.com/faceterteam/PayCards_iOS_Source/blob/3a340383da7b4874489b44a7ed2cee3dec2efb18/concat.sh#L1

it can help you to fix Unsupported architectures ... error

**Comment by Vitalik13** [comment]
@tchernitski do you mean that script need in fix?

**Comment by Vitalik13** [comment]
@vitkuzmenko Спасибо большое с помощью pod получилось

**Comment by vitkuzmenko** [comment]
@Vitalik13 хорошо. на этой неделе постараюсь сделать апдейт с кастомизацией
